// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASTq8bFITGR4Q8o4G8BriELBHlrGNSVTc',
    appId: '1:1084909155275:web:f4f734e6812545f4ff7c4e',
    messagingSenderId: '1084909155275',
    projectId: 'guia-7-fcd64',
    authDomain: 'guia-7-fcd64.firebaseapp.com',
    storageBucket: 'guia-7-fcd64.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-bUyzbtqxhMQOYhS3qIEeadoFVN-kOEU',
    appId: '1:1084909155275:android:e50aaf7269e4ec90ff7c4e',
    messagingSenderId: '1084909155275',
    projectId: 'guia-7-fcd64',
    storageBucket: 'guia-7-fcd64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-0vcSKZtZt_FcrHylZesebP4aLx1j6Us',
    appId: '1:1084909155275:ios:8ceb1f1252051402ff7c4e',
    messagingSenderId: '1084909155275',
    projectId: 'guia-7-fcd64',
    storageBucket: 'guia-7-fcd64.firebasestorage.app',
    iosBundleId: 'com.example.activididad7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-0vcSKZtZt_FcrHylZesebP4aLx1j6Us',
    appId: '1:1084909155275:ios:8ceb1f1252051402ff7c4e',
    messagingSenderId: '1084909155275',
    projectId: 'guia-7-fcd64',
    storageBucket: 'guia-7-fcd64.firebasestorage.app',
    iosBundleId: 'com.example.activididad7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASTq8bFITGR4Q8o4G8BriELBHlrGNSVTc',
    appId: '1:1084909155275:web:9b215b96a36ad9d2ff7c4e',
    messagingSenderId: '1084909155275',
    projectId: 'guia-7-fcd64',
    authDomain: 'guia-7-fcd64.firebaseapp.com',
    storageBucket: 'guia-7-fcd64.firebasestorage.app',
  );
}
